### ISSUE TITLE
Is the key/value interface also a cache when using time to live on set operations

### ISSUE THREAD

**Issue by devigned** [WebAssembly/wasi-keyvalue#15]
The key/value read/write interface seems very close to what would be expected out of a cache interface. The missing part is setting a key with a time to live (ttl).

The question is, should there be two interfaces, k/v and cache, or just k/v?

@lukewagner I believe you have discussed cache in the past. It would be great to get your perspective on this topic.

**Comment by lukewagner** [comment]
Great observation, and I've been thinking about the same thing, in particular, whether there is only one "KV" interface with durability as a knob (expressed somehow), or whether there are two interfaces that just happen to look very similar.

I don't have a complete or fully thought-out answer, but here's some partial thoughts:

Regardless of whether we have a common interface or two different interfaces, I think we should have the distinction between durable-store and non-durable-cache show up in the Wit interface id string so we can see declaratively from a component's type whether it's importing, say, `wasi:keyvalue/durable` vs. `wasi:keyvalue/cache`.  If we go with two interfaces, that's as easy as saying that the `wasi:keyvalue` proposal contains two separate interfaces name, say, `durable` vs. `cache`.  If we want a shared interface, then you could say that we have one interface, say, `wasi:keyvalue/types` defining a common resource type, say `store`, that contains the common operations as resource methods, and then `wasi:keyvalue/durable`/`wasi:keyvalue/cache` are interfaces that simply contain a function that returns a handle to a `store`.

As for whether we should have the shared interface or two totally separate ones, I haven't thought hard enough to know whether the two interfaces are similar-enough to justify that.  As you said, TTL is an example of a parameter you'd want to see in `cache` ops... but does it make any sense in `durable` kv-store ops?  I'd be interested to hear more from anyone with experience across the spectrum of KV stores.  Conversely, there are various atomic ops that are common durable KV stores, but are these present in popular KV caches (like memcache)?

Next, just to confirm, it seems like our canonical examples of `wasi:keyvalue/cache` implementations would be memcache and redis; does that sound right?

Lastly, another thing I've learned is that there's also probably an additional need for a `wasi:http/cache` interface in the style of the Web's [`Cache`](https://developer.mozilla.org/en-US/docs/Web/API/Cache) API, where the key to the cache is an HTTP request and the value is an HTTP response.  Having an HTTP-specialized separate interface allows the implementation a bunch more optimization leeway to take advantage of the higher-level semantics of HTTP than if you attempted to implement an HTTP `Cache` on top of a plain `wasi:keyvalue/cache`.  (The `Cache` API is used in both JS inside-the-browser and outside-the-browser so this is probably something we'll want to support if we want to run such JS in wasm.)

**Comment by Mossaka** [comment]
>  I'd be interested to hear more from anyone with experience across the spectrum of KV stores. 

I will ask around. 

> it seems like our canonical examples of wasi:keyvalue/cache implementations would be memcache and redis; does that sound right?

yes, as far as I can tell, the most wildly used cache datastores are these two.

**Comment by lukewagner** [comment]
Thinking about it a bit more, we might be better off long-term having separate interfaces for durable KV stores vs. KV caches and not trying to share all KV store operations (although the fundamental types in `wasi:keyvalue/types` do seem like they could be shared).

A few reasons:
* The TTL parameter seems essential to caching, but maybe is not something we want to require for all durable kv stores in the basic interface.
* Having a strongly-consistent `compare-and-swap` seems problematic for any sort of distributed cache, and [not actually what you want](https://groups.google.com/g/redis-db/c/a4zK2k1Lefo/m/hOjM9iwDGhIJ) for the basic use case of "avoid a bunch of concurrent requests all redundantly computing the same value after they all miss".  Instead, iiuc, caches want some sort of `put-or-get` operation that allows (but does not require) concurrent requests to rendezvous (so that one computes the inserted value and the others wait and get the inserted value).  And I get the impression that this might be valuable enough (at scale) to belong in the basic `cache` interface.  However this might not make sense for a durable KV store or belong in the basic durable store interface.
* As we add interfaces for advanced/optional KV operations (e.g. `atomic`), they may only make sense for durable vs. cache, and a *particular component* may only need to import these operations for only one of durable-or-cache, so it seems useful to define these as separate interfaces with separate interface ids so that this is declaratively stated in the component's imports.

So, roughly speaking, I'm imagining something like this (taking "store" to mean "durable"):
```wit
package wasi:keyvalue
interface types {
  type key = ...
  type incoming-value = ...
  type outgoing-value = ...
}
interface store {
   use types.{key, incoming-value, outgoing-value}
   type bucket = ...
   open: func(name: string) -> bucket
   get: func(b: bucket, k: key) -> result<incoming-value, error>
   set: func(b: bucket, k: key, v: outgoing-value) -> result<_, error>
   ...
}
interface cache {
   use types.{key, incoming-value, outgoing-value}
   type bucket = ...
   open: func(name: string) -> bucket
   get: func(b: bucket, k: key, ttl-ms: u32) -> result<incoming-value, error>
   set: func(b: bucket, k: key, ttl-ms: u32) -> result<_, error>
   ...
} 
```
(where later these operations could be methods of `bucket`.)  It's a bit sad to see all the partial duplication, but (1) it's not that many, (2) we have bindings generation so it's not like we're trying to absolutely minimize the number; we can be the opposite of `ioctl`.

But I'll admit these are still just partially-formed opinions.  WDYT?

**Comment by c00kiemon5ter** [comment]
@lukewagner I expect the `set` interface for the cache was meant to include the value too

```wit
interface cache {
   ...
   set: func(b: bucket, k: key, v: outgoing-value, ttl-ms: u32) -> result<_, error>
```

---

Is anyone working on such an interface? Is there a "wasi-cache" repo?
